[package]
name = "rodalies-sim"
version = "0.1.0"
edition = "2021"
description = "Simulador de tráfico ferroviario e incidencias hiperrealista para Rodalies de Barcelona, construido dinámicamente desde GTFS."
license = "MIT"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
csv = "1"
petgraph = "0.6"
rayon = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time", "net", "io-util"] }
rand = "0.8"
printpdf = "0.7"
zip = { version = "0.6", default-features = false, features = ["deflate"] }

[profile.release]
opt-level = 3
lto = "thin"
